Document: dotenv-cli
Title: Debian dotenv-cli Manual
Author: <insert document author here>
Abstract: This manual describes what dotenv-cli is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dotenv-cli/dotenv-cli.sgml.gz

Format: postscript
Files: /usr/share/doc/dotenv-cli/dotenv-cli.ps.gz

Format: text
Files: /usr/share/doc/dotenv-cli/dotenv-cli.text.gz

Format: HTML
Index: /usr/share/doc/dotenv-cli/html/index.html
Files: /usr/share/doc/dotenv-cli/html/*.html
